function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
}

export function siteLockPage(returnTo: string, nonce: string, error: string) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#050507"><meta name="robots" content="noindex,nofollow"><title>Enter MyDancr</title><style nonce="${escapeHtml(nonce)}">
*{box-sizing:border-box}html{color-scheme:dark}body{margin:0;min-height:100svh;display:grid;place-items:center;padding:24px;background:#050507;color:#f7f7fa;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{width:100%;max-width:380px;padding:32px 24px;background:#101014;border:1px solid #2d2d36;border-radius:20px}.brand{margin:0 0 36px;font-size:30px;font-weight:800;letter-spacing:-1.8px}.brand span{color:#a78bfa}.lock{width:28px;height:28px;color:#a78bfa;margin-bottom:12px}h1{margin:0 0 8px;font-size:25px;line-height:1.25;letter-spacing:-.5px}.intro{margin:0 0 24px;color:#b8b8c5;font-size:14px;line-height:1.5}label{display:block;margin-bottom:8px;font-size:13px;font-weight:600}input,button{width:100%;min-height:48px;border-radius:10px;font:inherit}input{padding:12px 14px;color:#fff;background:#08080b;border:1px solid #4b4b59}input:focus-visible,button:focus-visible{outline:2px solid #c4b5fd;outline-offset:3px}button{margin-top:16px;padding:12px 16px;border:1px solid #9563f2;background:#6d28d9;color:#fff;font-weight:700;cursor:pointer}button:hover{background:#7c3aed}.error{margin:12px 0 0;font-size:13px;line-height:1.5;color:#ddd0ff}@media(max-width:360px){body{padding:16px}main{padding:28px 20px}}
</style></head><body><main><p class="brand">mydanc<span>r</span></p><svg class="lock" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></svg><h1>Enter MyDancr</h1><p class="intro">Enter the site password to continue.</p><form action="/site-unlock" method="post"><input type="hidden" name="returnTo" value="${escapeHtml(returnTo)}"><label for="site-password">Password</label><input id="site-password" name="password" type="password" autocomplete="current-password" maxlength="128" required${error ? ' aria-invalid="true" aria-describedby="password-error"' : ""}>${error ? `<p class="error" id="password-error" role="alert">${escapeHtml(error)}</p>` : ""}<button type="submit">Enter site</button></form></main></body></html>`;
}
