import test from'node:test';import assert from'node:assert/strict';
import{createAgentDatabase,seedAgents,insertAgent,insertAgentChain,assignAgent,agentId,agentSnapshot,graphLocks,agentSchema,agentMigration}from'./helpers/agent-hierarchy-database.mjs';
const admissionProbe=`create function public.synthetic_graph_lock_probe()returns trigger language plpgsql as $$begin
 if not exists(select 1 from pg_locks where locktype='advisory' and pid=pg_backend_pid()and granted)then raise exception 'SYNTHETIC_GRAPH_LOCK_MISSING';end if;return new;end$$;
 create trigger aaa_synthetic_graph_lock_probe before insert or update of sponsor_agent_id,status,commission_depth_limit on public.sales_agents for each row execute function public.synthetic_graph_lock_probe()`;
test('original graph validation reaches row validation without a shared write lock',async t=>{
 const db=await createAgentDatabase({migrate:false});t.after(()=>db.close());await seedAgents(db);await db.exec('reset role;'+admissionProbe+';set role service_role');await assert.rejects(insertAgent(db),/SYNTHETIC_GRAPH_LOCK_MISSING/);assert.equal((await db.query('select count(*)::int n from public.sales_agents')).rows[0].n,0);
});
test('serialized hierarchy retains actual validation, access and transaction behavior',async t=>{
 const db=await createAgentDatabase();t.after(()=>db.close());
 t.beforeEach(()=>seedAgents(db));
 await t.test('real schemas retain all captured constraints and target function identities',async()=>{
  assert.equal(agentSchema.columns.length,30);assert.equal(agentSchema.constraints.length,23);assert.equal(agentSchema.indexes.length,9);
  for(const f of agentSchema.functions.filter(f=>!['assign_admin_venue_sales_agent','attribute_approved_venue_agent_referral'].includes(f.name)))assert.equal((await db.query('select md5(pg_get_functiondef($1::regprocedure))hash',['public.'+f.signature])).rows[0].hash,f.fingerprint);
  const installed=(await db.query("select prosecdef,proacl::text,proconfig from pg_proc where oid='public.lock_sales_agent_hierarchy_writes()'::regprocedure")).rows[0];assert.equal(installed.prosecdef,false);assert.equal(installed.proacl,'{postgres=X/postgres}');assert.deepEqual(installed.proconfig,['search_path=pg_catalog, public, pg_temp','lock_timeout=3s']);
 });
 await t.test('the statement lock is already held before the first row validator',async()=>{
  await db.exec('reset role;'+admissionProbe+';set role service_role');try{await insertAgent(db);await db.query("update public.sales_agents set status='suspended'where id=$1",[agentId(10)]);}finally{await db.exec('reset role;drop trigger aaa_synthetic_graph_lock_probe on public.sales_agents;drop function public.synthetic_graph_lock_probe();set role service_role');}
 });
 for(const[field,value]of[['sponsor_agent_id',null],['status','suspended'],['commission_depth_limit',5]])await t.test(field+' writes take the same transaction lock and release it on commit',async()=>{
  await insertAgent(db);await db.exec('begin');try{await db.query('update public.sales_agents set '+field+'=$1 where id=$2',[value,agentId(10)]);const locks=await graphLocks(db);assert.equal(locks.length,1);assert.equal(locks[0].mode,'ExclusiveLock');assert.equal(locks[0].objsubid,1);assert.equal(locks[0].granted,true);const hash=(await db.query("select (hashtextextended('mydancr:sales-agent-hierarchy',0)>>32 & 4294967295)::text high,(hashtextextended('mydancr:sales-agent-hierarchy',0)&4294967295)::text low")).rows[0];assert.equal(locks[0].classid,hash.high);assert.equal(locks[0].objid,hash.low);await db.exec('commit');assert.deepEqual(await graphLocks(db),[]);}finally{await db.exec('rollback');}
 });
 await t.test('insert and repeated upsert statements reuse one lock until rollback',async()=>{
  await db.exec('begin');try{for(let i=0;i<2;i++)await db.query("select public.set_admin_sales_agent($1,$2,null,3::smallint,'active')",[agentId(1),agentId(10)]);assert.equal((await graphLocks(db)).length,1);assert.equal((await db.query('select count(*)::int n from public.admin_actions')).rows[0].n,2);}finally{await db.exec('rollback');}assert.deepEqual(await graphLocks(db),[]);assert.equal((await db.query('select count(*)::int n from public.sales_agents')).rows[0].n,0);
 });
 await t.test('unrelated referral-code edits do not acquire the hierarchy lock',async()=>{await insertAgent(db);await db.exec('begin');try{await db.query("update public.sales_agents set referral_code=repeat('a',36)where id=$1",[agentId(10)]);assert.deepEqual(await graphLocks(db),[]);}finally{await db.exec('rollback');}});
 await t.test('Repeatable Read rejects graph changes without rows or audit',async()=>{const before=await agentSnapshot(db);await db.exec('begin isolation level repeatable read');try{await assert.rejects(insertAgent(db),e=>e.code==='25000'&&/Read Committed/.test(e.message));}finally{await db.exec('rollback');}assert.deepEqual(await agentSnapshot(db),before);});
 await t.test('Serializable graph writes remain supported',async()=>{await db.exec('begin isolation level serializable');try{await insertAgent(db);await db.exec('commit');}finally{await db.exec('rollback');}assert.equal((await db.query('select count(*)::int n from public.sales_agents')).rows[0].n,1);});
 await t.test('self-sponsorship is rejected',async()=>{await assert.rejects(insertAgent(db,{sponsor:10}),/cannot sponsor their own/);});
 await t.test('indirect cycles are rejected while valid reparenting succeeds',async()=>{await insertAgentChain(db,{length:3});const before=await agentSnapshot(db);await assert.rejects(db.query('update public.sales_agents set sponsor_agent_id=$1 where id=$2',[agentId(10),agentId(12)]),/circular agent hierarchy/);assert.deepEqual(await agentSnapshot(db),before);await db.query('update public.sales_agents set sponsor_agent_id=null where id=$1',[agentId(10)]);await db.query('update public.sales_agents set sponsor_agent_id=$1 where id=$2',[agentId(10),agentId(12)]);});
 await t.test('a multirow update cannot introduce a two-agent cycle',async()=>{await insertAgent(db);await insertAgent(db,{id:11});const before=await agentSnapshot(db);await assert.rejects(db.query('update public.sales_agents set sponsor_agent_id=case when id=$1 then $2::uuid else $1::uuid end where id in($1,$2)',[agentId(10),agentId(11)]),/circular agent hierarchy/);assert.deepEqual(await agentSnapshot(db),before);});
 for(const[depth,status]of[[null,'active'],[3,null],[4,'active'],[3,'unknown']])await t.test('administrator setter rejects depth/status '+String(depth)+'/'+String(status),async()=>{const before=await agentSnapshot(db);await assert.rejects(db.query('select public.set_admin_sales_agent($1,$2,null,$3::smallint,$4)',[agentId(1),agentId(10),depth,status]),e=>['22023','23502'].includes(e.code));assert.deepEqual(await agentSnapshot(db),before);});
 for(const status of['suspended','terminated'])await t.test(status+' sponsors reject a new child',async()=>{await insertAgent(db,{id:11,status});await assert.rejects(insertAgent(db,{sponsor:11}),/must be an active sales agent/);});
 for(const[field,value,code]of[['status','invalid','23514'],['status',null,'23502'],['commission_depth_limit',4,'23514'],['commission_depth_limit',null,'23502'],['user_id',null,'23502'],['referral_code','bad','23514']])await t.test(field+' rejects '+String(value)+' without changing a row',async()=>{await insertAgent(db);const before=await agentSnapshot(db);await assert.rejects(db.query('update public.sales_agents set '+field+'=$1 where id=$2',[value,agentId(10)]),e=>e.code===code);assert.deepEqual(await agentSnapshot(db),before);});
 await t.test('only one active five-level founder is allowed',async()=>{await insertAgent(db,{depth:5});await assert.rejects(insertAgent(db,{id:11,depth:5}),e=>e.code==='23505');});
 for(const[role,user]of[['anon',null],['authenticated',agentId(2)],['authenticated',agentId(3)]])await t.test(role+' '+String(user)+' cannot create or invoke privileged graph writes',async()=>{await db.exec('set role '+role);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user||'']);await assert.rejects(insertAgent(db),e=>e.code==='42501');await assert.rejects(db.query("select public.set_admin_sales_agent($1,$2,null,3::smallint,'active')",[agentId(1),agentId(10)]),e=>e.code==='42501');});
 await t.test('active administrator direct writes still pass RLS and take the graph lock',async()=>{await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[agentId(1)]);await db.exec('begin');try{await insertAgent(db);assert.equal((await graphLocks(db)).length,1);}finally{await db.exec('rollback');}});
 await t.test('mandatory administrator audit failure rolls the upsert back',async()=>{await db.exec("reset role;create function public.synthetic_agent_audit_failure()returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_AGENT_AUDIT_FAILURE';end$$;create trigger synthetic_agent_audit_failure before insert on public.admin_actions for each row execute function public.synthetic_agent_audit_failure();set role service_role");const before=await agentSnapshot(db);try{await assert.rejects(db.query("select public.set_admin_sales_agent($1,$2,null,3::smallint,'active')",[agentId(1),agentId(10)]),/SYNTHETIC_AGENT_AUDIT_FAILURE/);assert.deepEqual(await agentSnapshot(db),before);}finally{await db.exec('reset role;drop trigger synthetic_agent_audit_failure on public.admin_actions;drop function public.synthetic_agent_audit_failure();set role service_role');}});
 await t.test('financial agent rows remain undeletable',async()=>{await insertAgent(db);await assert.rejects(db.exec('delete from public.sales_agents'),/Financial records cannot be deleted/);});
 await t.test('incorrect trigger attachment is rejected before side effects',async()=>{await db.exec('reset role;create trigger synthetic_wrong_agent_context before insert on public.venues for each statement execute function public.lock_sales_agent_hierarchy_writes();set role service_role');try{await assert.rejects(db.query('insert into public.venues values($1,true)',[agentId(103)]),/Invalid sales-agent hierarchy trigger context/);}finally{await db.exec('reset role;drop trigger synthetic_wrong_agent_context on public.venues;set role service_role');}});
});
test('both attribution writers preserve one bounded ancestor snapshot and atomic history',async t=>{
 const db=await createAgentDatabase();t.after(()=>db.close());t.beforeEach(()=>seedAgents(db));
 for(const length of[1,2,3,4,5,6,8])for(const route of['administrator','approval'])await t.test(route+' snapshots '+length+'-agent chain',async()=>{
  await insertAgentChain(db,{length});let attributionId;
  if(route==='administrator')attributionId=await assignAgent(db);else{await db.query("insert into public.venue_signup_requests values($1,'pending',$2,$3,$4,'2026-01-01T00:00:00Z')",[agentId(200),agentId(10),agentId(100),agentId(1)]);await db.query("update public.venue_signup_requests set status='approved'where id=$1",[agentId(200)]);}
  const row=(await db.query('select * from public.venue_sales_attributions')).rows[0];if(attributionId)assert.equal(row.id,attributionId);assert.equal(row.signing_agent_id,agentId(10));for(let depth=1;depth<=5;depth++)assert.equal(row['sponsor_level_'+depth+'_agent_id'],depth<length?agentId(10+depth):null);assert.equal(new Date(row.effective_from).toISOString(),'2026-01-01T00:00:00.000Z');assert.equal((await db.query('select count(*)::int n from public.admin_actions')).rows[0].n,1);assert.deepEqual(await graphLocks(db),[]);
 });
 await t.test('both installed callers retain a single recursive snapshot statement',async()=>{for(const name of['assign_admin_venue_sales_agent','attribute_approved_venue_agent_referral']){const definition=(await db.query('select pg_get_functiondef(oid) d from pg_proc where pronamespace=\'public\'::regnamespace and proname=$1',[name])).rows[0].d;assert.equal((definition.match(/with recursive sponsors as/g)||[]).length,1);assert.equal(definition.includes('select sponsor_agent_id into'),false);assert.match(definition,/where sponsors.depth < 5/);assert.equal(definition.includes('pg_advisory'),false);}assert.match(agentMigration,/before insert or update of sponsor_agent_id, status, commission_depth_limit\s+on public.sales_agents for each statement/);});
 await t.test('replacement snapshots new ancestry while preserving the earlier attribution',async()=>{await insertAgentChain(db,{length:6});const original=await assignAgent(db);await db.query('update public.sales_agents set sponsor_agent_id=null where id=$1',[agentId(11)]);await assignAgent(db,{effective:'2026-02-01T00:00:00Z'});const rows=(await db.query('select * from public.venue_sales_attributions order by effective_from')).rows;assert.equal(rows.length,2);assert.equal(rows[0].id,original);assert.equal(rows[0].sponsor_level_5_agent_id,agentId(15));assert.equal(new Date(rows[0].superseded_at).toISOString(),'2026-02-01T00:00:00.000Z');assert.equal(rows[1].sponsor_level_1_agent_id,agentId(11));assert.equal(rows[1].sponsor_level_2_agent_id,null);assert.equal(rows[1].superseded_at,null);});
 for(const[description,options,message]of[['inactive admin',{actor:agentId(3)},'Admin access'],['inactive venue',{venue:agentId(102)},'active venue'],['missing signer',{signer:agentId(29)},'active signing agent'],['empty agreement',{reference:''},'agreement reference'],['null effective',{effective:null},'effective time']])await t.test(description+' rejects attribution atomically',async()=>{await insertAgent(db);const before=await agentSnapshot(db);await assert.rejects(assignAgent(db,options),new RegExp(message));assert.deepEqual(await agentSnapshot(db),before);});
 await t.test('replacement at or before the existing start remains invalid',async()=>{await insertAgent(db);await assignAgent(db);const before=await agentSnapshot(db);for(const effective of['2026-01-01T00:00:00Z','2025-12-01T00:00:00Z'])await assert.rejects(assignAgent(db,{effective}),/must begin after/);assert.deepEqual(await agentSnapshot(db),before);});
 await t.test('approval with no referral or an unchanged approved status adds no attribution',async()=>{await db.query("insert into public.venue_signup_requests values($1,'pending',null,$2,$3,null)",[agentId(200),agentId(100),agentId(1)]);await db.exec("update public.venue_signup_requests set status='approved';update public.venue_signup_requests set status='approved'");assert.equal((await db.query('select count(*)::int n from public.venue_sales_attributions')).rows[0].n,0);});
 await t.test('duplicate approval attribution rolls back the request update',async()=>{await insertAgent(db);await assignAgent(db);await db.query("insert into public.venue_signup_requests values($1,'pending',$2,$3,$4,null)",[agentId(200),agentId(10),agentId(100),agentId(1)]);const before=await agentSnapshot(db);await assert.rejects(db.exec("update public.venue_signup_requests set status='approved'"),/already has an active sales-agent attribution/);assert.deepEqual(await agentSnapshot(db),before);});
 for(const[venue,reviewer]of[[null,agentId(1)],[agentId(100),null]])await t.test('referral trigger requires both verified workspace and administrator '+String(venue)+'/'+String(reviewer),async()=>{await insertAgent(db);await db.query("insert into public.venue_signup_requests values($1,'pending',$2,$3,$4,'2026-01-01T00:00:00Z')",[agentId(200),agentId(10),venue,reviewer]);const before=await agentSnapshot(db);await assert.rejects(db.exec("update public.venue_signup_requests set status='approved'"),/verified workspace and administrator/);assert.deepEqual(await agentSnapshot(db),before);});
 for(const route of['administrator','approval'])await t.test(route+' rejects a suspended signer atomically',async()=>{await insertAgent(db,{status:'suspended'});if(route==='approval')await db.query("insert into public.venue_signup_requests values($1,'pending',$2,$3,$4,'2026-01-01T00:00:00Z')",[agentId(200),agentId(10),agentId(100),agentId(1)]);const before=await agentSnapshot(db);await assert.rejects(route==='administrator'?assignAgent(db):db.exec("update public.venue_signup_requests set status='approved'"),/active signing agent|no longer active/);assert.deepEqual(await agentSnapshot(db),before);});
 for(const route of['administrator','approval'])await t.test(route+' audit failure restores attribution and request history',async()=>{await insertAgent(db);if(route==='approval')await db.query("insert into public.venue_signup_requests values($1,'pending',$2,$3,$4,null)",[agentId(200),agentId(10),agentId(100),agentId(1)]);else await assignAgent(db);await db.exec("reset role;create function public.synthetic_attribution_failure()returns trigger language plpgsql as $$begin raise exception 'SYNTHETIC_ATTRIBUTION_FAILURE';end$$;create trigger synthetic_attribution_failure before insert on public.admin_actions for each row execute function public.synthetic_attribution_failure();set role service_role");const before=await agentSnapshot(db);try{await assert.rejects(route==='administrator'?assignAgent(db,{effective:'2026-02-01T00:00:00Z'}):db.exec("update public.venue_signup_requests set status='approved'"),/SYNTHETIC_ATTRIBUTION_FAILURE/);assert.deepEqual(await agentSnapshot(db),before);}finally{await db.exec('reset role;drop trigger synthetic_attribution_failure on public.admin_actions;drop function public.synthetic_attribution_failure();set role service_role');}});
});
