import test from'node:test';import assert from'node:assert/strict';
import{createNfcCapacityDatabase,seedNfcCapacity,insertTags,provisionTag,rotateTag,setTagStatus,activeTags,nfcCapacitySnapshot,capId,asBrowser,nfcCapacityMigration}from'./helpers/nfc-capacity-database.mjs';
const atCapacity=p=>assert.rejects(p,e=>e.code==='54000'&&/25 active NFC/.test(e.message));
test('the same NFC capacity applies to all existing writers without losing history',async t=>{
 const db=await createNfcCapacityDatabase();t.after(()=>db.close());
 async function scenario(name,fn){await t.test(name,async()=>{await seedNfcCapacity(db);await fn();});}
 await scenario('provisioning claims the final slot with one audit record',async()=>{await insertTags(db,{count:24});const tag=await provisionTag(db);assert.equal(tag.status,'active');assert.equal(await activeTags(db),25);assert.equal((await nfcCapacitySnapshot(db)).audit.length,1);});
 await scenario('provisioning beyond capacity is rejected with records intact',async()=>{await insertTags(db,{count:25});const before=await nfcCapacitySnapshot(db);await atCapacity(provisionTag(db));assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('enabling a disabled sticker cannot claim the twenty-sixth slot',async()=>{await insertTags(db,{count:25});await insertTags(db,{start:200,status:'disabled'});const before=await nfcCapacitySnapshot(db);await atCapacity(setTagStatus(db,{id:200}));assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('disabled sticker rotation cannot claim the twenty-sixth slot',async()=>{await insertTags(db,{count:25});await insertTags(db,{start:200,status:'disabled'});const before=await nfcCapacitySnapshot(db);await atCapacity(rotateTag(db,{id:200}));assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('rotation at capacity atomically replaces one occupied slot',async()=>{await insertTags(db,{count:25});const tag=await rotateTag(db);assert.equal(tag.status,'active');assert.equal(tag.rotated_from_tag_id,capId(100));assert.equal(await activeTags(db),25);const snapshot=await nfcCapacitySnapshot(db);assert.equal(snapshot.tags.length,26);assert.equal(snapshot.tags.find(t=>t.id===capId(100)).status,'revoked');assert.equal(snapshot.audit.length,1);});
 await scenario('disabled rotation can claim the final slot and preserve old history',async()=>{await insertTags(db,{count:24});await insertTags(db,{start:200,status:'disabled'});await rotateTag(db,{id:200});assert.equal(await activeTags(db),25);const s=await nfcCapacitySnapshot(db);assert.equal(s.tags.find(t=>t.id===capId(200)).status,'revoked');assert.equal(s.tags.find(t=>t.id===capId(300)).rotated_from_tag_id,capId(200));});
 await scenario('enabling an already active sticker succeeds at capacity',async()=>{await insertTags(db,{count:25});await setTagStatus(db);assert.equal(await activeTags(db),25);});
 await scenario('disabling frees a slot for provisioning',async()=>{await insertTags(db,{count:25});await setTagStatus(db,{status:'disabled'});await provisionTag(db);assert.equal(await activeTags(db),25);});
 await scenario('a different venue has independent capacity',async()=>{await insertTags(db,{count:25});await provisionTag(db,{venue:capId(11)});assert.equal(await activeTags(db,capId(11)),1);});
 for(const type of['dressing_room','cashier'])await scenario(`${type} counts toward the same venue limit`,async()=>{await insertTags(db,{count:25});const before=await nfcCapacitySnapshot(db);await atCapacity(insertTags(db,{start:200,type}));assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 for(const status of['disabled','revoked'])await scenario(`${status} stickers do not occupy capacity`,async()=>{await insertTags(db,{count:25});await insertTags(db,{count:2,start:200,status});assert.equal(await activeTags(db),25);});
 await scenario('direct service insert cannot bypass capacity',async()=>{await insertTags(db,{count:25});await atCapacity(insertTags(db,{start:200}));assert.equal(await activeTags(db),25);});
 await scenario('multirow inserts that exceed capacity roll back entirely',async()=>{await insertTags(db,{count:24});const before=await nfcCapacitySnapshot(db);await atCapacity(insertTags(db,{count:2,start:200}));assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('multirow activation cannot claim one slot twice',async()=>{await insertTags(db,{count:24});await insertTags(db,{count:2,start:200,status:'disabled'});const before=await nfcCapacitySnapshot(db);await atCapacity(db.query("update public.nfc_tags set status='active' where status='disabled'"));assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('moving an active sticker cannot overfill its destination',async()=>{await insertTags(db,{count:25});await insertTags(db,{start:200,venue:capId(11)});const before=await nfcCapacitySnapshot(db);await atCapacity(db.query('update public.nfc_tags set venue_id=$1 where id=$2',[capId(10),capId(200)]));assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('moving into the last destination slot succeeds',async()=>{await insertTags(db,{count:24});await insertTags(db,{start:200,venue:capId(11)});await db.query('update public.nfc_tags set venue_id=$1 where id=$2',[capId(10),capId(200)]);assert.equal(await activeTags(db),25);assert.equal(await activeTags(db,capId(11)),0);});
 await scenario('ignored duplicate inserts and existing-slot upserts remain idempotent',async()=>{await insertTags(db,{count:25});const before=await nfcCapacitySnapshot(db);await db.query('insert into public.nfc_tags select * from public.nfc_tags where id=$1 on conflict(id) do nothing',[capId(100)]);assert.deepEqual(await nfcCapacitySnapshot(db),before);await db.query("insert into public.nfc_tags select * from public.nfc_tags where id=$1 on conflict(id) do update set status=excluded.status,label='Updated label'",[capId(100)]);assert.equal(await activeTags(db),25);});
 await scenario('token collision rolls back revocation and audit',async()=>{await insertTags(db,{count:2});const before=await nfcCapacitySnapshot(db);await assert.rejects(rotateTag(db,{digest:String(101).padStart(64,'0')}),e=>e.code==='23505');assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 for(const[operation,call]of[['provision',()=>provisionTag(db,{id:400})],['enable',()=>setTagStatus(db,{id:200})],['rotate',()=>rotateTag(db)]])await scenario(`${operation} rolls back when mandatory audit fails`,async()=>{
  await insertTags(db);await insertTags(db,{start:200,status:'disabled'});const before=await nfcCapacitySnapshot(db);await db.exec('reset role;alter table public.admin_actions add constraint synthetic_failure check(false);set role service_role');
  try{await assert.rejects(call(),e=>e.code==='23514');assert.deepEqual(await nfcCapacitySnapshot(db),before);}finally{await db.exec('reset role;alter table public.admin_actions drop constraint synthetic_failure;set role service_role');}
 });
 for(const[actor,label]of[[capId(2),'venue owner'],[capId(3),'customer'],[capId(4),'inactive admin'],[null,'missing actor']])await scenario(`${label} cannot use admin sticker RPCs`,async()=>{await insertTags(db);const before=await nfcCapacitySnapshot(db);for(const call of[()=>provisionTag(db,{actor}),()=>setTagStatus(db,{actor}),()=>rotateTag(db,{actor})])await assert.rejects(call(),e=>e.code==='42501');assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 for(const[role,id,label]of[['anon',null,'anonymous'],['authenticated',capId(2),'venue owner'],['authenticated',capId(3),'customer'],['authenticated',capId(4),'inactive administrator']])await scenario(`${label} retains direct-write and RPC denial`,async()=>{await insertTags(db,{count:25});const before=await nfcCapacitySnapshot(db);await asBrowser(db,role,id);await assert.rejects(insertTags(db,{start:200}),e=>e.code==='42501');await assert.rejects(provisionTag(db),e=>e.code==='42501');await db.exec('set role service_role');assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('an authenticated active admin sees the full count and cannot bypass it',async()=>{await insertTags(db,{count:25});await insertTags(db,{start:200,status:'disabled'});const before=await nfcCapacitySnapshot(db);await asBrowser(db,'authenticated',capId(1));assert.equal(await activeTags(db),25);await atCapacity(insertTags(db,{start:300}));await atCapacity(db.query("update public.nfc_tags set status='active' where id=$1",[capId(200)]));await db.exec('set role service_role');assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 for(const input of[{label:null},{label:' '},{label:'x'.repeat(81)},{type:null},{type:'unknown'},{digest:null},{digest:'not-a-digest'},{id:null}])await scenario(`invalid provisioning input ${Object.keys(input)[0]}=${String(Object.values(input)[0])} fails atomically`,async()=>{const before=await nfcCapacitySnapshot(db);await assert.rejects(provisionTag(db,input),e=>['22023','23502','23514'].includes(e.code));assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('invalid status and secret cannot change a sticker',async()=>{await insertTags(db);const before=await nfcCapacitySnapshot(db);for(const status of[null,'unknown'])await assert.rejects(setTagStatus(db,{status}),e=>['22023','23502','23514'].includes(e.code));for(const digest of[null,'bad'])await assert.rejects(rotateTag(db,{digest}),e=>['22023','23502','23514'].includes(e.code));assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('revoked stickers remain rejected by current status/rotation functions',async()=>{await insertTags(db,{status:'revoked'});const before=await nfcCapacitySnapshot(db);await assert.rejects(setTagStatus(db),e=>e.code==='P0002');await assert.rejects(rotateTag(db),e=>e.code==='P0002');assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('new capacity function has no API execution grant',async()=>{for(const role of['anon','authenticated','service_role'])assert.equal((await db.query("select has_function_privilege($1,'public.enforce_active_venue_nfc_capacity()','execute') allowed",[role])).rows[0].allowed,false);});
 await scenario('provision, enable and rotation acquire the same venue lock',async()=>{await insertTags(db);await insertTags(db,{start:200,status:'disabled'});await db.exec('begin');try{await provisionTag(db,{id:300});await setTagStatus(db,{id:200});await rotateTag(db,{replacement:400});const locks=(await db.query("select classid::text,objid::text,mode,granted from pg_locks where locktype='advisory'")).rows;assert.equal(locks.length,1);const expected=(await db.query("select ((h>>32)&4294967295)::text classid,(h&4294967295)::text objid from(select hashtextextended('mydancr:venue-active-nfc-slots:'||$1::text,0) h)x",[capId(10)])).rows[0];assert.equal(locks[0].classid,expected.classid);assert.equal(locks[0].objid,expected.objid);assert.equal(locks[0].mode,'ExclusiveLock');assert.equal(locks[0].granted,true);}finally{await db.exec('rollback');}assert.equal((await db.query("select count(*)::int n from pg_locks where locktype='advisory'")).rows[0].n,0);});
 await scenario('different venues acquire distinct locks released at commit',async()=>{await db.exec('begin');try{await provisionTag(db);await provisionTag(db,{id:300,venue:capId(11)});assert.equal((await db.query("select count(*)::int n from pg_locks where locktype='advisory'")).rows[0].n,2);await db.exec('commit');}catch(e){await db.exec('rollback');throw e;}assert.equal((await db.query("select count(*)::int n from pg_locks where locktype='advisory'")).rows[0].n,0);});
 await scenario('repeatable-read cannot activate a slot on an earlier snapshot',async()=>{await insertTags(db,{status:'disabled'});const before=await nfcCapacitySnapshot(db);await db.exec('begin isolation level repeatable read');try{await assert.rejects(setTagStatus(db),e=>e.code==='25000');}finally{await db.exec('rollback');}assert.deepEqual(await nfcCapacitySnapshot(db),before);});
 await scenario('serializable slot admission remains available',async()=>{await db.exec('begin isolation level serializable');try{await provisionTag(db);await db.exec('commit');}catch(e){await db.exec('rollback');throw e;}assert.equal(await activeTags(db),1);});
});
for(const[method,call]of[['enable',db=>setTagStatus(db,{id:200})],['disabled rotation',db=>rotateTag(db,{id:200})]])test(`current ${method} reproduces twenty-six active stickers; migration preserves history`,async t=>{const db=await createNfcCapacityDatabase({migrate:false});t.after(()=>db.close());await seedNfcCapacity(db);await insertTags(db,{count:25});await insertTags(db,{start:200,status:'disabled'});await call(db);assert.equal(await activeTags(db),26);const before=await nfcCapacitySnapshot(db);await db.exec('reset role');await db.exec(nfcCapacityMigration);await db.exec('set role service_role');assert.deepEqual(await nfcCapacitySnapshot(db),before);await atCapacity(insertTags(db,{start:400}));});
