begin isolation level repeatable read read only;
set local search_path=pg_catalog,public,pg_temp;
set local statement_timeout='30s';
set local lock_timeout='3s';
select jsonb_build_object(
 'captured_at',clock_timestamp(),'read_only',current_setting('transaction_read_only'),
 'enums',(select coalesce(jsonb_agg(to_jsonb(x) order by name),'[]') from (select t.typname name,array_agg(e.enumlabel order by e.enumsortorder) labels from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_enum e on e.enumtypid=t.oid where n.nspname='public' group by t.typname)x),
 'domains',(select coalesce(jsonb_agg(to_jsonb(x) order by name),'[]') from (select t.typname name,format_type(t.typbasetype,t.typtypmod) base_type,t.typnotnull not_null,t.typdefault default_value from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname='public' and t.typtype='d')x),
 'relations',(select coalesce(jsonb_agg(to_jsonb(x) order by name),'[]') from (select c.oid object_oid,c.relname name,c.relkind kind,c.relpersistence persistence,c.relrowsecurity rls,c.relforcerowsecurity force_rls,c.reloptions options,pg_get_userbyid(c.relowner) owner,case when c.relkind in ('v','m') then pg_get_viewdef(c.oid,true) end view_definition from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p','v','m','f'))x),
 'columns',(select coalesce(jsonb_agg(to_jsonb(x) order by table_name,position),'[]') from (select c.relname table_name,a.attnum position,a.attname name,format_type(a.atttypid,a.atttypmod) type,a.attnotnull not_null,a.attidentity identity_kind,a.attgenerated generated,pg_get_expr(d.adbin,d.adrelid) default_value,case when a.attcollation<>0 and a.attcollation<>(select typcollation from pg_type where oid=a.atttypid) then a.attcollation::regcollation::text end collation from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname='public' and c.relkind in ('r','p') and a.attnum>0 and not a.attisdropped)x),
 'constraints',(select coalesce(jsonb_agg(to_jsonb(x) order by table_name,name),'[]') from (select c.conname name,r.relname table_name,c.contype kind,pg_get_constraintdef(c.oid) definition from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and c.contype<>'n')x),
 'indexes',(select coalesce(jsonb_agg(to_jsonb(x) order by name),'[]') from (select i.indexrelid::regclass::text name,pg_get_indexdef(i.indexrelid) definition from pg_index i join pg_class c on c.oid=i.indrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and not exists(select 1 from pg_constraint k where k.conindid=i.indexrelid))x),
 'functions',(select coalesce(jsonb_agg(to_jsonb(x) order by signature),'[]') from (select p.oid::regprocedure::text signature,p.proname name,pg_get_functiondef(p.oid) definition,pg_get_userbyid(p.proowner) owner from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prokind in ('f','p'))x),
 'triggers',(select coalesce(jsonb_agg(to_jsonb(x) order by schema_name,table_name,name),'[]') from (select n.nspname schema_name,c.relname table_name,t.tgname name,t.tgenabled enabled,pg_get_triggerdef(t.oid) definition from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid join pg_namespace pn on pn.oid=p.pronamespace where not t.tgisinternal and pn.nspname='public' and n.nspname in ('public','auth','storage'))x),
 'policies',(select coalesce(jsonb_agg(to_jsonb(p) order by schemaname,tablename,policyname),'[]') from pg_policies p where schemaname in ('public','storage')),
 'sequences',(select coalesce(jsonb_agg(to_jsonb(x) order by name),'[]') from (select c.relname name,format_type(s.seqtypid,null) type,s.seqstart::text start,s.seqincrement::text increment,s.seqmax::text max,s.seqmin::text min,s.seqcache::text cache,s.seqcycle cycle,d.deptype dependency_kind,t.relname owner_table,a.attname owner_column from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_sequence s on s.seqrelid=c.oid left join pg_depend d on d.classid='pg_class'::regclass and d.objid=c.oid and d.refclassid='pg_class'::regclass and d.deptype in ('a','i') left join pg_class t on t.oid=d.refobjid left join pg_attribute a on a.attrelid=t.oid and a.attnum=d.refobjsubid where n.nspname='public')x),
 'relation_grants',(select coalesce(jsonb_agg(to_jsonb(x) order by name,grantee,privilege_type),'[]') from (select c.relname name,c.relkind kind,case when acl.grantee=0 then 'PUBLIC' else pg_get_userbyid(acl.grantee) end grantee,acl.privilege_type,acl.is_grantable from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(coalesce(c.relacl,acldefault(case when c.relkind='S' then 'S'::"char" else 'r'::"char" end,c.relowner)))acl where n.nspname='public' and c.relkind in ('r','p','v','m','f','S'))x),
 'column_grants',(select coalesce(jsonb_agg(to_jsonb(x) order by table_name,column_name,grantee,privilege_type),'[]') from (select c.relname table_name,a.attname column_name,case when acl.grantee=0 then 'PUBLIC' else pg_get_userbyid(acl.grantee) end grantee,acl.privilege_type,acl.is_grantable from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(a.attacl)acl where n.nspname='public' and a.attnum>0 and not a.attisdropped)x),
 'function_grants',(select coalesce(jsonb_agg(to_jsonb(x) order by signature,grantee,privilege_type),'[]') from (select p.oid::regprocedure::text signature,case when acl.grantee=0 then 'PUBLIC' else pg_get_userbyid(acl.grantee) end grantee,acl.privilege_type,acl.is_grantable from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f'::"char",p.proowner)))acl where n.nspname='public' and p.prokind in ('f','p'))x),
 'default_grantees',(select coalesce(jsonb_agg(distinct case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end),'[]') from pg_default_acl d cross join lateral aclexplode(d.defaclacl)a where d.defaclnamespace=0 or d.defaclnamespace='public'::regnamespace),
 'type_grants',(select coalesce(jsonb_agg(to_jsonb(x) order by name,grantee,privilege_type),'[]') from (select t.typname name,pg_get_userbyid(t.typowner) owner,case when acl.grantee=0 then 'PUBLIC' else pg_get_userbyid(acl.grantee) end grantee,acl.privilege_type,acl.is_grantable from pg_type t join pg_namespace n on n.oid=t.typnamespace cross join lateral aclexplode(coalesce(t.typacl,acldefault('T'::"char",t.typowner)))acl where n.nspname='public' and t.typtype in ('e','d'))x),
 'schema_grants',(select coalesce(jsonb_agg(to_jsonb(x) order by grantee,privilege_type),'[]') from (select case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end grantee,a.privilege_type,a.is_grantable from pg_namespace n cross join lateral aclexplode(coalesce(n.nspacl,acldefault('n',n.nspowner)))a where n.nspname='public')x),
 'default_acl',(select coalesce(jsonb_agg(to_jsonb(x) order by owner,schema_name,kind),'[]') from (select pg_get_userbyid(d.defaclrole) owner,coalesce(n.nspname,'') schema_name,d.defaclobjtype kind,d.defaclacl::text acl from pg_default_acl d left join pg_namespace n on n.oid=d.defaclnamespace where d.defaclrole=(select oid from pg_roles where rolname='postgres') and (d.defaclnamespace=0 or n.nspname='public'))x),
 'default_privileges',(select coalesce(jsonb_agg(to_jsonb(x) order by owner,schema_name,kind,grantee,privilege_type),'[]') from (select pg_get_userbyid(d.defaclrole) owner,coalesce(n.nspname,'') schema_name,d.defaclobjtype kind,case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end grantee,a.privilege_type,a.is_grantable from pg_default_acl d left join pg_namespace n on n.oid=d.defaclnamespace cross join lateral aclexplode(d.defaclacl)a where d.defaclrole=(select oid from pg_roles where rolname='postgres') and (d.defaclnamespace=0 or n.nspname='public'))x),
 'storage_grants',(select coalesce(jsonb_agg(to_jsonb(x) order by name,grantee,privilege_type),'[]') from (select c.relname name,case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end grantee,a.privilege_type,a.is_grantable from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner)))a where n.nspname='storage' and c.relname in ('objects','buckets'))x),
 'storage_column_grants',(select coalesce(jsonb_agg(to_jsonb(x) order by table_name,column_name,grantee,privilege_type),'[]') from (select c.relname table_name,a.attname column_name,case when acl.grantee=0 then 'PUBLIC' else pg_get_userbyid(acl.grantee) end grantee,acl.privilege_type,acl.is_grantable from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(a.attacl)acl where n.nspname='storage' and c.relname in ('objects','buckets') and a.attnum>0 and not a.attisdropped)x),
 'buckets',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'public',public,'file_size_limit',file_size_limit,'allowed_mime_types',allowed_mime_types) order by id),'[]') from storage.buckets),
 'extensions',(select jsonb_agg(jsonb_build_object('name',e.extname,'schema',n.nspname,'version',e.extversion) order by e.extname) from pg_extension e join pg_namespace n on n.oid=e.extnamespace),
 'ledger',(select coalesce(jsonb_agg(jsonb_build_object('version',version,'name',name,'sql_md5',md5(array_to_string(statements,E'\n'))) order by version),'[]') from supabase_migrations.schema_migrations)
) as replay_schema;
rollback;
