"""Embed the five existing profile logos as text glyphs instead of dimmable images.

Run with Python and fonttools[woff]==4.66.0 installed. This is an authoring step;
production serves the generated font embedded in the checked-in stylesheet.
"""

import argparse
import base64
import io
from pathlib import Path
import re
import xml.etree.ElementTree as ET

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.cu2quPen import Cu2QuPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.svgLib.path import parse_path


ROOT = Path(__file__).resolve().parents[1]
CSS = ROOT / "public/dancr-aesthetic.v1.css"
SOURCE = ROOT / "src/live-shell/app/07-shift-window-for-date.js"
PLATFORMS = ("instagram", "tiktok", "snapchat", "onlyfans", "x")
START = "/* BEGIN PROFILE SOCIAL FONT - generated by scripts/generate-profile-social-font.py */"
END = "/* END PROFILE SOCIAL FONT */"


def circle(cx, cy, radius, clockwise=True):
    sweep = int(clockwise)
    return (f"M{cx + radius} {cy}"
            f"A{radius} {radius} 0 1 {sweep} {cx - radius} {cy}"
            f"A{radius} {radius} 0 1 {sweep} {cx + radius} {cy}Z")


def logo_paths(platform, source):
    match = re.search(rf"^\s*{platform}: '<span[^>]*>(<svg.*?</svg>)</span>'", source, re.M)
    if not match:
        raise ValueError(f"Missing original {platform} logo")
    svg = ET.fromstring(match[1])
    if platform == "instagram":
        # Expand the original 2px strokes into closed font outlines. Opposite
        # contour directions keep the frame and camera lens holes transparent.
        return [
            "M9 3H15A6 6 0 0 1 21 9V15A6 6 0 0 1 15 21H9A6 6 0 0 1 3 15V9A6 6 0 0 1 9 3Z",
            "M9 5A4 4 0 0 0 5 9V15A4 4 0 0 0 9 19H15A4 4 0 0 0 19 15V9A4 4 0 0 0 15 5H9Z",
            circle(12, 12, 4.4), circle(12, 12, 2.4, False), circle(17.2, 6.8, 1),
        ]
    paths = [node.attrib["d"] for node in svg.findall("path")]
    if platform == "onlyfans":
        paths = [circle(9.2, 12, 5.4), circle(9.2, 12, 2.15, False), *paths]
    return paths


def font_bytes():
    source = SOURCE.read_text(encoding="utf-8")
    glyphs = {".notdef": TTGlyphPen(None).glyph()}
    for platform in PLATFORMS:
        pen = TTGlyphPen(None)
        curves = Cu2QuPen(pen, max_err=0.5, reverse_direction=True)
        coordinates = TransformPen(curves, (1000 / 24, 0, 0, -1000 / 24, 0, 1000))
        for outline in logo_paths(platform, source):
            parse_path(outline, coordinates)
        glyphs[platform] = pen.glyph()

    builder = FontBuilder(1000, isTTF=True)
    builder.setupGlyphOrder(list(glyphs))
    builder.setupCharacterMap({0xE900 + index: name for index, name in enumerate(PLATFORMS)})
    builder.setupGlyf(glyphs)
    builder.setupHorizontalMetrics({name: (1000, getattr(glyph, "xMin", 0)) for name, glyph in glyphs.items()})
    builder.setupHorizontalHeader(ascent=1000, descent=0, lineGap=0)
    builder.setupOS2(sTypoAscender=1000, sTypoDescender=0, sTypoLineGap=0, usWinAscent=1000, usWinDescent=0)
    builder.setupNameTable({
        "familyName": "MyDancr Profile Socials", "styleName": "Regular",
        "uniqueFontIdentifier": "MyDancrProfileSocials-Regular-1",
        "fullName": "MyDancr Profile Socials", "psName": "MyDancrProfileSocials-Regular",
        "version": "Version 1.0",
    })
    builder.setupPost()
    builder.setupMaxp()
    builder.font["head"].created = builder.font["head"].modified = 2082844800
    builder.font.recalcTimestamp = False
    builder.font.flavor = "woff2"
    result = io.BytesIO()
    builder.font.save(result)
    return result.getvalue()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    encoded = base64.b64encode(font_bytes()).decode("ascii")
    block = (f'{START}\n@font-face {{\n  font-family: "MyDancr Profile Socials";\n'
             f'  src: url("data:font/woff2;base64,{encoded}") format("woff2");\n'
             f'  font-style: normal;\n  font-weight: 400;\n  font-display: block;\n}}\n{END}')
    current = CSS.read_text(encoding="utf-8")
    updated, count = re.subn(re.escape(START) + r"[\s\S]*?" + re.escape(END), lambda _: block, current)
    if count != 1:
        raise ValueError("Expected exactly one generated font block")
    if args.check:
        if updated != current:
            raise ValueError("Profile social font is stale; rerun this generator")
    elif updated != current:
        CSS.write_text(updated, encoding="utf-8", newline="\n")
    print("Profile social font: five logos generated and verified.")


if __name__ == "__main__":
    main()
