-- Preserve the exact agreement and server-recorded assent independently of
-- user-editable Auth metadata. This migration does not accept for existing users.
begin;
set local lock_timeout = '5s';
set local statement_timeout = '30s';

create table public.dancer_agreement_versions (
  version text primary key,
  is_current boolean not null default false,
  source_sha256 text not null check (source_sha256 ~ '^[a-f0-9]{64}$'),
  content_sha256 text not null check (content_sha256 ~ '^[a-f0-9]{64}$'),
  document_html text not null,
  consent_text text not null,
  created_at timestamptz not null default now()
);
create unique index dancer_agreement_one_current on public.dancer_agreement_versions (is_current) where is_current;

insert into public.dancer_agreement_versions(version, is_current, source_sha256, content_sha256, document_html, consent_text)
values ('2026-09-17-v4', true, '1632164791070c5684c1f577c03194ed7d465f858a18bb6c561ca272d58f6e1e', '41a406a6ae6d96541e0d34a34412e7500af0987eeead420e86ebfb9754394071', $document$<p>MyDancr.com (&quot;Website&quot;) is a social media website and application service that allows Dancers to upload photos and videos to their profile, (&quot;Service&quot;).</p>
<p>These Terms of Service, together with our Privacy Policy (&quot;Terms&quot;), govern your use of MyDancr.com, including any content, functionality, and services offered on or through the Website. By registering with and usingMyDancr.com, you hereby accept and agree to be bound by and abide by these Terms. If you do not want to agree to these Terms, you must not access or use the Website.</p>
<p>This Website is offered and available to users who are 18 years of age or older. By using this Website, you represent and warrant that you are of legal age to form a binding contract with us and meet all of the foregoing eligibility requirements. If you do not meet all of these requirements, you must not access or use the Website.</p>
<p>These Terms are a binding contract between you, an individual user (&quot;Dancer&quot;;) and MyDancr LLC (“MyDancr LLC or MyDancr”), governing your use of the Website and Service. BY ACCESSING THE WEBSITE AND/OR USING THE SERVICE, YOU AGREE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THIS DANCER AGREEMENT. IF YOU DO NOT AGREE, YOU MAY NOT ACCESS OR USE THE SERVICE. CONTACT MYDANCR LLC AT <a href="mailto:support@mydancr.com">support@mydancr.com</a> IF YOU WANT MYDANCR LLC TO SEND YOU A COPY OF THIS AGREEMENT AND MYDANCR LLC’S PRIVACY POLICY.</p>
<p>My Dancr LLC is not a talent agent and is not licensed under  any state as a talent agent or as an employment agent or otherwise, or as a theatrical employment agency or other employment agency, and MyDancr LLC has not promised to procure employment or engagements for any of its performers. The Dancer is responsible for the Dancer&#x27;s own relationship with each club, including classification, pay, tips, fees, scheduling, taxes, licensing, work cards, safety, and conduct. MyDancr does not direct the Dancer&#x27;s performance work, set service prices, collect payment for dancer services, or guarantee customers, shifts, income, or admission.</p>
<p>The Dancer acknowledges that MyDancr is not a security service, emergency-response provider, transportation provider, employer, or operator of any club or venue. For any immediate threat or safety emergency, the Dancer must contact 911, law enforcement, appropriate emergency services, and/or club security. MyDancr support is not an emergency service and does not monitor reports in real time.</p>
<p>The Dancer is responsible for making personal safety and transportation decisions while traveling to a club, entering or remaining at a club, working or performing at a club, leaving a club, and traveling home or to any other destination. To the fullest extent permitted by applicable law, the Dancer knowingly assumes the risks associated with those activities and releases and holds harmless MyDancr and its owners, officers, employees, contractors, affiliates, and agents from claims arising from accidents, transportation, assault, harassment, theft, injury, misconduct, unsafe venue conditions, or the actions of clubs, patrons, employees, drivers, or other third parties during those periods.</p>
<h2 id="dancer-agreement-section-1">ELIGIBILITY AND TRUTHFUL IDENTITY.</h2><p>The Dancer represents that the Dancer is at least 18, is the person operating the account, has legal capacity, and may lawfully work and publish the submitted content. The dancer must provide accurate stage identity and city information and must not use another person&#x27;s documents, likeness, stage identity, or account. A stage name may be public; any legal identity collected independently by a club, tax authority, or other provider is governed by that relationship and applicable law.</p>
<p>The Dancer must maintain all local work cards, entertainer licenses, permits, immigration/work authorization, and club requirements. A MyDancr badge or affiliation does not replace government or club verification.</p>
<h2 id="dancer-agreement-section-2">PROFILE APPROVAL AND CLUB AFFILIATIONS.</h2><p>Before the profile becomes public, the Dancer must make the required eligibility and truthful-account representations, complete the required profile fields, obtain approval of required media, and submit the profile. MyDancr alone decides whether the profile is eligible for publication under its account, profile, media, visibility, and safety rules. A club does not approve the Dancer&#x27;s profile or affiliation. A club affiliation is a separate status established by a validated dressing-room NFC tap and is not a general identity, age, employment, licensing, or safety guarantee.</p>
<p>An affiliation is established automatically when MyDancr validates the Dancer&#x27;s intentional tap on the club&#x27;s official dressing-room NFC tag; no club representative approval or confirmation is required. An authorized club user may remove that affiliation through the venue dashboard. The Dancer may post a club-specific shift or use Working Now at a club only while the applicable NFC-established affiliation is active and must promptly correct an inaccurate schedule or notify MyDancr of an inaccurate affiliation.</p>
<h2 id="dancer-agreement-section-3">PUBLIC PROFILE AND SCHEDULE VISIBILITY.</h2><p>When you publish your profile or schedule, you authorize public display of your stage name, city, approved media, public social links, club affiliations, posted shifts, and Working Now status, as applicable. This information can reveal where you work and when you expect to be there. Public information may be copied or indexed by others. Available profile and schedule controls let you change what MyDancr displays, but MyDancr cannot guarantee removal of copies independently retained by third parties.</p>
<h2 id="dancer-agreement-section-4">WORKING NOW AND NFC PRESENCE EVENTS.</h2><p>Working Now requires an intentional dressing-room NFC tap validated by MyDancr. The Dancer authorizes collection of the club, time of the event, browser or device information, IP address, the applicable NFC tag, and information reasonably necessary to validate the event, operate the time window, and prevent fraud. The Dancer may not share or copy a tag, simulate a tap, use automation, or ask another person to check in.</p>
<p>Working Now is time-limited and does not promise that the Dancer remains continuously on premises or is available to any customer. The Dancer should end an inaccurate status through available controls and notify support of a malfunction.</p>
<h2 id="dancer-agreement-section-5">NFC AND TECHNICAL INTEGRITY.</h2><p>The Dancer may not copy, move, alter, obscure, damage, replace, emulate, relay, or misuse an NFC tag; simulate a tap; falsify redemption or verification information; gain unauthorized access; introduce malicious code; scrape or interfere with the Service; or access data outside their authorized permissions.</p>
<h2 id="dancer-agreement-section-6">NFC ASSURANCE.</h2><p>NFC tags are assigned by purpose and club. A validated tap on an official dressing-room tag establishes the Dancer&#x27;s affiliation and can support time-limited Working Now presence; cashier tags support deal verification. MyDancr&#x27;s technical validation of the NFC event is required, but no club representative approval is required. Tags should be installed in controlled areas and replaced if lost, copied, or compromised. MyDancr does not use geofences or continuous or background location tracking for these functions. The applicable intentional NFC tap is the sole in-club verification event.</p>
<p>MATERIAL TERMS: As provided in greater detail in these Terms, you acknowledge the following:</p>
<p>(a) the Service is licensed, not sold to you, and that you may use the Service only as set forth in this Agreement;</p>
<p>(b) the use of the Service may be subject to separate third-party terms of service and fees, including, without limitation, your mobile network operator’s terms of service and fees, including fees charged for data usage and overage, which are your sole responsibility.</p>
<p>The Service presents pictures of semi-nude and audiovisual works depicting semi-nude females. You understand that by using this Service, and by merely accessing this Website, you may be exposed to content that can be considered by some to be offensive, indecent, or objectionable.</p>
<p>You agree not to reproduce, duplicate, copy, sell, distribute, rent, resell or exploit any portion of the Website, Service, use of the Service, or access to the Service; you consent to the collection, use, and disclosure of your personally identifiable information in accordance with MyDancr LLC’s Privacy Policy.</p>
<p>The Website and Service is provided “as is” without warranties of any kind and MyDancr LLC’s liability to you is limited.</p>
<h2 id="dancer-agreement-section-7">SCOPE OF LICENSE.</h2><p>MyDancr provides public promotional profiles, approved photos and videos, MyDancr TV, club affiliations, schedule and Working Now information, and related discovery features. Subject to this Agreement, you may access the Service on compatible devices you own or control and use its authorized features to promote your own lawful professional profile and club appearances. The Service is licensed, not sold, to you for use only under the terms of this agreement, complete and ongoing compliance with the terms of this agreement. MyDancr LLC hereby grants you a personal, limited, revocable, non-transferable license to use the Service on a single compatible device that you own or control, solely for your own private, personal, non-commercial use. You may not make the Service available over a network where it could be used by multiple devices at the same time. You may not rent, lease, lend, redistribute or sublicense the Service. You may not attempt to derive the source code of, modify, or create derivative works of the Service, any updates, or any part thereof (except as and only to the extent any foregoing restriction is prohibited by applicable law). If you breach these license restrictions or the restrictions, or otherwise exceed the scope of the licenses granted herein, then you may be subject to prosecution and damages, as well as liability for infringement of intellectual property rights. The terms of this agreement will govern any updates provided to you by MyDancr LLC that replace and/or supplement the original Terms, unless such upgrade is accompanied by a separate license or revised Terms, in which case the terms of that license or revised Terms will govern.</p>
<p>We reserve the right to make changes to these Terms at any time and at our sole discretion. All changes are effective immediately when we post them and apply to all access to and use of the Website thereafter. By continuing to use MyDancr.com after such notice, you agree to these Terms as modified. You are expected to check this page from time to time so you are aware of any changes, as they are binding on you.</p>
<p>By using MyDancr.com you consent to receiving communications from us electronically, including emails and messages posted to your MyDancr.com account,</p>
<p>You acknowledge and agree that all communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. If you wish to withdraw our consent to receiving communications from us at any time, please email <a href="mailto:support@mydancr.com">support@mydancr.com</a>, notifying us of your withdrawal of consent.</p>
<p>We reserve the right at any time and without notice to:</p>
<p>(a) modify, suspend or terminate the Service or any portion thereof;</p>
<p>(b) restrict, limit, suspend or terminate your access to the Service or any portion thereof;</p>
<p>(c) delete any content you post on MyDancr.com if in our reasonable opinion it does not comply with these Terms and/or applicable law;</p>
<p>(d) monitor your use of the Service (including any content or message you post or broadcast on MyDancr.com) to verify compliance with these Terms and/or any applicable law;</p>
<p>(e) investigate any suspected or alleged misuse or unlawful use of the Service and cooperate with law enforcement in such investigation;</p>
<p>(f) disclose information about your use of the Service in connection with law enforcement investigation of any suspected or alleged illegal activity, or in response to a lawful court order; or</p>
<p>From time to time, we may restrict access to some parts of the Website, or the entire Website, to Dancers.</p>
<h2 id="dancer-agreement-section-8">PRIVACY POLICY.</h2><p>Your use of the Website and Service is subject to the Privacy Policy, which is hereby incorporated by reference into these Terms. By using the Website and/or Service, you agree that you have read, understood, and agree to the data collection, use, and disclosure provisions set forth in the Privacy Policy.</p>
<h2 id="dancer-agreement-section-9">MOBILE SERVICES.</h2><p>The Service includes certain services that are available via a mobile device, including (a) the ability to browse the Service from a mobile device; and (b) the ability to access certain features of the Service through Service Applications downloaded and installed on a mobile device (collectively, the “Mobile Services”). To the extent that you access the Service through a mobile device, your wireless service carrier’s standard charges, data rates and other fees may apply, and you acknowledge that you are solely responsible for all such fees and charges. In addition, your carrier may restrict downloading, installing, or using certain Mobile Services, and not all Mobile Services may work with all carriers or devices.</p>
<h2 id="dancer-agreement-section-10">SERVICE SECURITY.</h2><p>You are prohibited from violating, or attempting to violate, the security of the Service. Any such violations may result in criminal and/or civil penalties against you, as well as the termination of your privilege to use the Service, at MyDancr LLC’s sole discretion. MyDancr LLC reserves the right to investigate any alleged or suspected violations and, if a criminal violation is suspected, refer such suspected violation to the appropriate law enforcement agencies and cooperate fully with such investigations, including, but not limited to, the disclosure of any or all of your activities on or related to the Service. You agree to promptly notify MyDancr LLC if you learn or reasonably suspect that any security breach related to the Service has occurred.</p>
<h2 id="dancer-agreement-section-11">REGISTRATION AND ELIGIBILITY.</h2><p>To access certain additional features and functionality of the Service, you must register an account with MyDancr.com. All information provided to MyDancr LLC during registration will be held and used in accordance with MyDancr.com’s Privacy Policy. You are responsible for maintaining the confidentiality of your log-in credentials in order to use the Service and are fully responsible for all activities that occur through the use of your credentials. You agree to notify MyDancr LLC immediately of any unauthorized use of your log-in credentials or any other breach of security with respect to your account. MyDancr LLC will not be liable for any loss or damage arising from unauthorized use of your credentials prior to you notifying MyDancr LLC of such unauthorized use or loss of your credentials.</p>
<h2 id="dancer-agreement-section-12">ACCURACY OF INFORMATION.</h2><p>You agree to provide true, accurate, current, and complete information about yourself as requested in any registration forms and to update the information about yourself promptly, and as necessary, to keep it current and accurate.</p>
<h2 id="dancer-agreement-section-13">ACCOUNT DEACTIVATION AND DELETION.</h2><p>You may disable or request deletion of your account through Account Settings, or contact <a href="mailto:support@mydancr.com">support@mydancr.com</a> for assistance. Disabling an account and deleting an account have different effects. Account deletion does not necessarily remove records we must retain for the limited purposes described in the Privacy Policy.</p>
<h2 id="dancer-agreement-section-14">ADVERTISEMENTS.</h2>
<p>(a) Third Party Advertisements. MyDancr LLC may display advertisements for the goods and services of third parties or other promotional materials on the Service. Your dealings with, or participation in, promotions of any third-party advertisers on the Service, are solely between you and such third party, and your participation is subject to any terms and conditions associated with that advertisement or promotion. MyDancr LLC does not endorse or represent such third parties, and by using the Service, you agree that MyDancr LLC is not responsible or liable for any loss or damage of any sort incurred as a result of any such dealings or the presence of such third parties on the Service.</p>
<p>(b) Third Party Sites. The Service may also include links to third party websites or third-party services that are not owned or operated by MyDancr LLC (collectively, “Third-Party Sites”). MyDancr LLC does not endorse or represent such third parties andMyDancr LLC is not responsible for the availability of these Third-Party Sites, or any products, services and/or content contained therein. You agree that we are not responsible or liable, directly or indirectly, for any loss or damage of any sort incurred as a result of your use of or reliance on any Third-Party Sites. Certain functionalities of the Service may also require that you agree to additional terms and conditions of Third-Party Sites. You agree that you are solely responsible for your acceptance of and compliance with such terms and conditions whenever you use or access such Third-Party Sites.</p>
<p>(c) Social links and off-platform conduct. Supported social links may be displayed as &quot;Social links&quot; or equivalent neutral wording. The Dancer must control or be authorized to link each account. Links may not be used to evade MyDancr rules, solicit prohibited services, direct minors, mislead customers, or distribute malware. Third-party platform terms apply.</p>
<p>MyDancr does not monitor all off-platform conduct, but conduct connected to the Service may support enforcement when it creates safety, fraud, trafficking, impersonation, or legal risk.</p>
<p>CONTENT YOU SUBMIT; LICENSE GRANTS FROM YOU. A. Dancer Content. This Section governs any material that you post, send or transmit (collectively, “Post”) through the Service, including, by way of example and not limitation, photographs, graphics, images, text, musical works, sound recordings, digital phonorecord deliveries, and any other content, materials or works subject to protection under the laws of the United States or any other jurisdiction, including, but not limited to, patent, trademark, trade secret, and copyright laws (collectively, “Dancer Content”). You are solely responsible for securing the rights to any and all Dancer Content you Post to or through the Service.</p>
<p>(a) License Grants to MyDancr LLC and other Dancers. BY POSTING DANCER  CONTENT TO OR THROUGH THE SERVICE, YOU HEREBY GRANT TO MYDANCR LLC (AND MYDANCR LLC’S ASSIGNEES, DESIGNEES, SUCCESSORS, LICENSEES, AND SUB-LICENSEES) AN UNRESTRICTED, PERPETUAL, ASSIGNABLE, SUBLICENSABLE, REVOCABLE, ROYALTY-FREE, FULLY PAID UP LICENSE THROUGHOUT THE WORLD TO REPRODUCE, MODIFY, DISTRIBUTE, DISPLAY, PUBLISH, TRANSMIT, COMMUNICATE TO THE PUBLIC, MAKE AVAILABLE, BROADCAST, CREATE DERIVATIVE WORKS FROM, PUBLICLY PERFORM (INCLUDING ON A THROUGH-TO-THE AUDIENCE BASIS), DELIVER AND PUBLICLY PERFORM DIGITAL PHONORECORDS, AND OTHERWISE USE AND EXPLOIT (COLLECTIVELY, “USE”) ALL DANCER  CONTENT YOU POST TO OR THROUGH THE SERVICE, THROUGH ANY MEDIA AND FORMATS NOW KNOWN OR HEREAFTER DEVELOPED, IN CONNECTION WITH THE SERVICE, INCLUDING, WITHOUT LIMITATION, (A) IN CONNECTION WITH OR ON ANY THIRD PARTY SITES AND PLATFORMS WHERE THE SERVICE IS SYNDICATED; AND (B) TO ADVERTISE, MARKET AND PROMOTE THE AVAILABILITY OF DANCER  CONTENT AND THE SERVICE. BY WAY OF EXAMPLE ONLY AND WITHOUT LIMITING THE FOREGOING LICENSE, MYDANCR LLC WILL HAVE THE RIGHT TO INSERT, PLACE OR INCLUDE ALL TYPES OF ADVERTISEMENTS WITHIN OR AROUND DANCER  CONTENT, INCLUDING, WITHOUT LIMITATION, RUNNING OR STREAMING PRE-ROLLS, MID-ROLLS, POST-ROLLS, DISPLAY ADS, OVERLAYS, BANNERS, CAMPAIGN AND COMPANION ADS AND ANY OTHER TYPE OF ADVERTISING, WHETHER AUDIO, VISUAL, OR AUDIOVISUAL UNITS IN CONNECTION WITH DANCER  CONTENT. NOTWITHSTANDING THE PRECEDING SENTENCES OF THIS SECTION, IF YOU REMOVE ANY OF YOUR DANCER  CONTENT USING FUNCTIONALITIES AVAILABLE THROUGH THE SERVICE, THEN YOU AGREE TO, AND HEREBY DO GRANT, MYDANCR LLC A PERPETUAL AND IRREVOCABLE LICENSE TO USE ANY BACKUP COPIES OF YOUR DANCER  CONTENT THAT MYDANCR LLC MADE PRIOR TO YOUR REMOVAL OF YOUR DANCER  CONTENT AND IN THE ORDINARY COURSE OF BUSINESS.</p>
<p>(b) License for Name, Image, Voice, and Likeness. You further hereby grant MyDancr LLC a royalty-free license to Use your name, image, voice, trademarks, logos, monikers, and likeness (and that of any person identifiable in any Dancer Content you posted to or through the Service) made available by or on your behalf through the Service in conjunction with your Dancer Content. The foregoing license in the immediately preceding sentence will survive the termination of your account with respect to any of your Dancer Content Posted to the Service prior to such termination.</p>
<p>(c) Limited Waiver of Rights. You waive any and all rights of privacy, rights of publicity, or any other rights of a similar nature in connection with your Dancer Content, or any portion thereof. To the extent any moral rights are not transferable or assignable, you hereby waive and agree never to assert any and all moral rights, or to support, maintain or permit any action based on any moral rights that you may have in or with respect to any of your Dancer Content Posted to the Service, during the term of this agreement. You expressly release MyDancr LLC and all of MyDancr’s agents, partners, subsidiaries, affiliates, licensees, successors, and assigns from any and all claims, demands, liabilities, or causes of action, whether now known or unknown, for defamation, copyright infringement, violation of moral rights, and invasion of the rights to privacy, right to publicity, or personality or any similar matter, or based upon or relating to the Use of your Dancer Content as authorized in this agreement.</p>
<p>(d) Representations and Warranties with Respect to Your Dancer Content. Except for materials provided to you by MyDancr LLC and MyDancr.com through the Service, you represent, warrant, and covenant that (1) you either are the sole and exclusive owner of all of your Dancer Content, or you have all rights, licenses, consents, and releases that are necessary to grant to MyDancr LLC the rights in your Dancer Content as contemplated under this Dancer Agreement  ;  and (2) neither your Dancer Content nor your creation of, accessing, posting, submission or transmission of your Dancer Content will (x) infringe, misappropriate or violate the rights of any party or entity, including a third party’s patent, copyright, trademark, trade secret, moral rights, rights of publicity, rights of privacy or other intellectual property or proprietary rights; (y) constitute or result in defamation, libel, slander, or the violation of any applicable law or regulation (including, without limitation, restrictions on obscenity, child pornography, wiretap laws or other similar restrictions on nonconsensual recording, or otherwise); or (z) require MyDancr LLC to obtain any licenses from or make any payments in any amounts to any third party throughout the world.</p>
<p>(e) Proof of Rights Clearance. MyDancr LLC may require you to provide sufficient evidence of having all necessary rights, licenses, authorizations, permissions, and clearances for any of your Dancer Content that you Post to the Service, and if you fail to provide such evidence within a reasonable period of time (as determined by MyDancr LLC in its sole discretion), then MyDancr LLC may remove some or all of your Dancer Content from the Service and/or terminate your account, without any liability to you. You are solely responsible for keeping copies of such evidence.</p>
<p>(c) AGE DOCUMENTS MUST BE SUBMITTED FOR ALL DANCERS .</p>
<p>By appearing on MyDancr.com you are verifying that you have reached the age 18 and have submitted all proper documentation and age verification forms to perform on the website. Only individuals who have submitted proper documentation and have been approved to perform may appear on MyDancr.com.</p>
<p>(e) NO VIOLATION OF LAWS RE OBSCENITY OR MINORS.</p>
<p>The Dancer shall not violate any local community standard of &quot;obscenity&quot; during any performance related to this Agreement, including but not limited to the Dancer shall not depict or describe any act of a sexual nature. Additionally, during any performance related to this Agreement, the Dancer shall not depict or describe any minor activity or act of a sexual nature involving persons under the age of 18 years (including but not limited to sex of any kind, simulated sex, sexual conduct, masturbation, bondage, domination, sadomasochism, or others).</p>
<p>(g) NOT UNDER INFLUENCE OF ALCOHOL OR ILLEGAL DRUGS.</p>
<p>While giving any performance or taking any other action related to this Agreement, Dancer shall not be under the influence of alcohol or any illegal drug or controlled substance.</p>
<p>(j) IMAGE APPROVAL.</p>
<p>Images submitted to MyDancr.com for Dancer’s account must be approved by MyDancr LLC. Images graphic in nature or containing nudity will not be approved. MyDancr LLC reserves the right to approve or reject any image submitted.</p>
<p>(k) NONCONSENSUAL INTIMATE IMAGE REMOVAL.</p>
<p>Nonconsensual intimate images, including qualifying digitally altered or generated images, are prohibited. A depicted individual or authorized representative may submit a removal request through our designated reporting channel. Upon receipt of a valid request, we remove the reported material within 48 hours and make reasonable efforts to identify and remove known identical copies within that period. Send requests to <a href="mailto:support@mydancr.com">support@mydancr.com</a></p>
<p>(l) MODEL HARASSMENT.</p>
<p>MyDancr LLC does not condone dancer to dancer harassment. If you are found to be harassing, bothering, teasing, distracting and/or mocking other models (either as a model or a member), your account may be suspended or terminated. MyDancr LLC supports all dancers and wants everyone to succeed. We expect all dancers to behave maturely and support each other.</p>
<p>(m) ACCOUNT TERMINATION.</p>
<p>MyDancr may restrict or terminate access for violations of this Agreement, content requirements, account eligibility rules, or applicable law. MyDancr does not supervise or evaluate the Dancer’s performance work at a club.</p>
<p>(n) RULE AMENDMENTS.</p>
<p>We reserve the right to add to or amend any rule/guideline as it becomes necessary.</p>
<h2 id="dancer-agreement-section-15">USE RESTRICTIONS.</h2><p>Your rights to use the Service and the MyDancr LLC and MyDancr.com’s  Content are expressly conditioned on the following:</p>
<p>(a) You may access the Service for your personal entertainment purposes only solely as intended through the provided functionality of the Service and as permitted under this agreement.</p>
<p>(b) You may not copy, distribute, re-sell, alter, modify, create derivative works of, sell, license or in any way exploit any part of the Service or any MyDancr.com Content.</p>
<p>(c) You agree not to copy, reproduce, distribute, publish, display, perform, transmit, stream or broadcast any part of the Service or MyDancr.com Content without MyDancr.com’s prior written authorization, including, by way of example and not limitation, by doing or engaging in any of the following without MyDancr LLC’s prior express written consent:</p>
<p>1) altering, defacing, mutilating or otherwise bypassing any approved software through which the Service is made available; and</p>
<p>2) using any trademarks, service marks, design marks, logos, photographs or other content belonging to MyDancr LLC or obtained from the Service.</p>
<p>(d) You agree not to bypass, circumvent, damage or otherwise interfere with any security or other features of the Service designed to control the manner in which the Service is used, harvest or mine MyDancr.com’s Content from the Service, or otherwise access or use the Service in a manner inconsistent with individual human usage.</p>
<p>(e) You agree not to undertake, cause, permit or authorize the modification, creation of derivative works, translation, reverse engineering, decompiling, disassembling or hacking of any aspect of the Service or MyDancr.com’s Content or any part thereof, or attempt to do any of the foregoing, except and solely to the extent permitted by this Dancer Agreement, the authorized features of the Service or MyDancr.com’s Content, or by law, or otherwise attempt to use or access any portion of the Service other than as intended by MyDancr LLC.</p>
<p>(f) You agree not to use, display, mirror, frame or utilize framing techniques to enclose the Service or the MyDancr.com’s Content, or any portion thereof, through any other application or website, unless and solely to the extent MyDancr LLC makes available the means for embedding any part of the Service or the MyDancr.com’s Content.</p>
<p>(g). You agree not to access, tamper with, or use non-public areas of the Service, MyDancr.com’s (and its hosting company’s) computer systems and infrastructure, or the technical delivery systems of MyDancr.com’s providers or other Dancers.</p>
<p>(h) You agree not to harass, abuse, harm or advocate or incite harassment, abuse or harm of another person or group, including MyDancr LLC employees or the management or employees of any gentlemen’s clubs.</p>
<p>(i) You agree not to provide any false personal information to MyDancr.com.</p>
<p>(j) You agree not to create a false identify or impersonate another person or entity in any way.</p>
<p>(k) You agree not to create a new account with MyDancr.com, without MyDancr LLC’s express written consent if MyDancr LLC has previously disabled, suspended or terminated an account of yours for any reason whatsoever.</p>
<p>(l) You agree not to solicit, or attempt to solicit, personal information from other Dancers.</p>
<p>(m) You agree not to restrict, discourage or inhibit any person from using the Service, disclose personal information about a third person on the Service or obtained from the Service without the consent of such person, or collect information about Dancers of the Service.</p>
<p>(n) You agree not to use the Service, without MyDancr LLC’s express written consent, for any commercial purpose, including reselling, distributing, or communicating or facilitating any commercial advertisement or solicitation.</p>
<p>(o) You agree not to gain unauthorized access to the Service, to other Dancers’ accounts, names or personally identifiable information, or to other computers or websites connected or linked to the Service.</p>
<p>(p) You agree not to Post, transmit or otherwise make available, including in any of your Dancer Content, any virus, worm, spyware or any other computer code, file or program that may or is intended to disable, overburden, impair, damage or hijack the operation of any hardware, software or telecommunications equipment, or any other aspect of the Service or MyDancr.com’s Content or communications equipment and computers connected to the Service.</p>
<p>(q) You agree not to Post any Dancer Content that is or could be interpreted to be defamatory, libelous, inaccurate, unlawful, harmful, threatening, abusive, harassing, vulgar, offensive, obscene, pornographic, objectionable, or hateful, or that promotes discrimination, bigotry, racism, or hatred, as determined by MyDancr LLC in its sole discretion.</p>
<p>(r) You agree not to Post any Dancer Content that does or could be claimed to infringe any third party intellectual property or other rights, including the rights of privacy, publicity and confidentiality.</p>
<p>(s) You agree not to interfere with or disrupt the Service, networks or servers connected to the Service or violate the regulations, policies or procedures of such networks or servers.</p>
<p>(t) You agree not to violate any applicable federal, state or local laws or regulations (including, without limitation, any traffic laws and rules applicable when you use the Service in a vehicle) or this agreement through the use of the Service.</p>
<p>(u) You agree not to assist or permit any persons in engaging in any of the activities described above.</p>
<p>The MyDancr name, logo and all related names, logos, product and service names, designs, and slogans are trademarks of MyDancr LLC or our affiliates or licensors. You must not use such marks without our prior written permission. All other names, logos, product and service names, designs, and slogans on the Website are the trademarks of their respective owners.</p>
<h2 id="dancer-agreement-section-16">DMCA</h2>
<p>To comply with the U.S. Digital Millennium Copyright Act (Title 17, United States Code) (&quot;DMCA&quot;), we will respond to proper notifications of claimed copyright infringement and will take appropriate action including removing or disabling access to the allegedly infringing Dancer Content and, if deemed appropriate by MyDancr LLC, terminating the account of the Dancer who published the content.</p>
<p>To notify us of claimed copyright infringement, please contact our customer support team by email at <a href="mailto:support@mydancr.com">support@mydancr.com</a></p>
<p>Under the DMCA, a notification of claimed copyright infringement must include all of the following:</p>
<p>a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</p>
<p>identification of the copyrighted work claimed to have been infringed, or if multiple copyrighted works are covered by a single notification, a representative list of such works;</p>
<p>identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the service provider to locate the material;</p>
<p>information reasonably sufficient to permit the service provider to contact the complaining party, such as an address, telephone number, and if available, an electronic mail address at which the complaining party may be contacted;</p>
<p>a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>
<p>a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
<p>If we remove or disable access to your Content in response to a DMCA notification of claimed copyright infringement, we will make reasonable efforts to notify you, and you may make a counter-notification in writing with our Designated Agent listed above.</p>
<p>A DMCA counter-notification must include all of the following:</p>
<p>your physical or electronic signature;</p>
<p>identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</p>
<p>a statement by you under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification; and your name, address, and telephone number, and a statement that you consent to the jurisdiction of which you are located and that you will accept service of process from the person who filed the notice of copyright infringement or an agent of such person.</p>
<p>If we receive a proper counter-notification from you, we will notify the party alleging copyright infringement and will reinstate your Dancer Content that was removed or disabled within 30 business days following our receipt of your counter-notification, unless the party alleging copyright infringement notifies us first that it/he/she has filed a court action against you.</p>
<p>Please note that, under the DMCA, any person who knowingly makes material misrepresentations in a notification of claimed infringement or in a counter-notification may be liable for damages.</p>
<h2 id="dancer-agreement-section-17">REPEAT INFRINGER POLICY.</h2><p>MyDancr LLC’s intellectual property policy is to (a) remove or disable access to material that MyDancr believes in good faith, upon notice from an intellectual property owner or his or her agent, is infringing the intellectual property of a third party by being made available through the Service; and (b) remove any Dancer Content you uploaded to the Service if you are a “repeat infringer” and terminate your right to use the Service. You are a “repeat infringer” if you are a Dancer that has uploaded Dancer Content or Feedback to or through the Service and for whom MyDancr LLC has received more than two takedown notices compliant with the provisions of 17 U.S.C. § 512 with respect to your Dancer Content or Feedback. MyDancr LLC has discretion, however, to terminate the account of any Dancer after receipt of a single notification of claimed infringement or upon MyDancr LLC’s own determination.</p>
<h2 id="dancer-agreement-section-18">INDEMNITY.</h2><p>You agree to indemnify and hold MyDancr LLC, and its officers, directors, employees, agents, successors, and assigns harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected to (a) your access, use, or misuse of the Service, or MyDancr’s Content; (b) your Dancer Content; or (c) your violation of this agreement. MyDancr will use reasonable efforts to notify you of any such claim, action or proceeding for which it seeks an indemnification from you upon becoming aware of it, but if MyDancr LLC is unable to communicate with you in a timely manner because of an inactive e-mail address for you, your indemnification obligation will continue notwithstanding MyDancr LLC’s inability to contact you in a timely manner. MyDancr LLC reserves the right to assume the exclusive defense and control of any matter that is subject to indemnification under this Section. In such case, you agree to cooperate with any reasonable requests to assist MyDancr LLC’s defense of such matter. You agree not to settle any matter without the prior express written consent of MyDancr LLC.</p>
<h2 id="dancer-agreement-section-19">NO WARRANTY.</h2><p>YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE SERVICE IS AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE, AND ANY CONTENT OR MATERIALS AVAILABLE THROUGH THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY DANCER CONTENT, THIRD PARTY CONTENT AND/OR MYDANCR LLC’s CONTENT), ARE PROVIDED “AS IS” AND “AS AVAILABLE,” WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND MYDANCR LLC HEREBY DISCLAIMS, ON BEHALF OF ITSELF AND ITS SUPPLIERS AND LICENSORS, ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE SERVICE, AND ANY CONTENT OR MATERIALS AVAILABLE THROUGH THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY DANCER CONTENT, THIRD PARTY CONTENT AND/OR MYDANCR LLC’s CONTENT), WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY, OF QUIET ENJOYMENT, TITLE, AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS. MYDANCR LLC DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE SERVICE, THAT THE FUNCTIONS CONTAINED IN OR SERVICES PERFORMED OR PROVIDED BY THE SERVICE WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE OR NOT INTERFERE WITH YOUR USE OR ENJOYMENT OF ANY OTHER APPLICATIONS ON THE DEVICE ON WHICH THE SERVICE IS ACCESSED OR INSTALLED, OR THAT DEFECTS IN THE SERVICE WILL BE CORRECTED. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY MYDANCR LLC OR ITS AUTHORIZED REPRESENTATIVES WILL CREATE A WARRANTY NOT EXPRESSLY PROVIDED FOR IN THIS DANCER AGREEMENT. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU, BUT IN SUCH A CASE THE FOREGOING WILL BE APPLIED TO THE GREATEST EXTENT ENFORCEABLE UNDER APPLICABLE LAW.</p>
<h2 id="dancer-agreement-section-20">LIMITATION OF LIABILITY.</h2><p>TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT WILL MYDANCR LLC OR ITS SUPPLIERS OR LICENSORS BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR INABILITY TO USE THE SERVICE AND ANY CONTENT OR MATERIALS AVAILABLE THROUGH THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY DANCER CONTENT, THIRD PARTY CONTENT AND/OR MYDANCR LLC’s CONTENT), HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT OR OTHERWISE) AND EVEN IFMYDANCR LLC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. IN NO EVENT WILL MYDANCR LLC’S TOTAL LIABILITY TO YOU FOR ALL DAMAGES (OTHER THAN AS MAY BE REQUIRED BY APPLICABLE LAW IN CASES INVOLVING PERSONAL INJURY EXCEED ONE HUNDRED DOLLARS ($100.00). THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF OR LIMITATION OF CERTAIN TYPES OF DAMAGES OR LIABILITIES, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU, BUT IN SUCH A CASE THE FOREGOING WILL BE APPLIED TO THE GREATEST EXTENT ENFORCEABLE UNDER APPLICABLE LAW.</p>
<h2 id="dancer-agreement-section-21">DISPUTE RESOLUTION AND MANDATORY ARBITRATION.</h2><p>Please read this carefully. It affects your rights. YOU AND MYDANCR LLC AND EACH OF OUR RESPECTIVE CORPORATE PARENTS, SUBSIDIARIES, AFFILIATES, PREDECESSORS IN INTEREST, SUCCESSORS, PERMITTED ASSIGNS, AND ANY OTHER PARTIES ON WHOSE BEHALF YOU ARE ACCESSING THE SERVICE AGREE TO ARBITRATION, AS THE EXCLUSIVE FORM OF DISPUTE RESOLUTION FOR ALL DISPUTES AND CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE SERVICE. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, allows for more limited discovery than in court, and is subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. Please visit www.adr.org for more information about arbitration.</p>
<p>(a) Commencing Arbitration. A party who intends to seek arbitration must first send to the other, by certified mail, a written notice of intent to arbitrate (a “Notice”), or, if you do not provide a mailing address to MyDancr LLC, to you via any other method available to MyDancr LLC, including via e-mail. The Notice to MyDancr LLC should be addressed to the Legal Department. The Notice must (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought (the “Demand”). If you and MyDancr LLC do not reach an agreement to resolve the claim within 90 days after the Notice is received, then you or MyDancr LLC may commence an arbitration proceeding as set forth below or file a claim in small claims court. THE ARBITRATION WILL BE ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION (“AAA”) IN ACCORDANCE WITH ITS COMMERCIAL ARBITRATION RULES AND THE SUPPLEMENTARY PROCEDURES FOR CONSUMER RELATED DISPUTES (THE “Rules”), AS MODIFIED BY THIS AGREEMENT. The Rules and AAA forms are available online at www.adr.org. You are solely responsible for the payment of the filing fee.</p>
<p>(b) Arbitration Proceeding. The arbitration will be conducted in the English language. A single independent and impartial arbitrator will be appointed pursuant to the Rules, as modified herein. You and MyDancr LLC agree to comply with the following rules, which are intended to streamline the dispute resolution process and reduce the costs and burdens on the parties: (a) the arbitration will be conducted by telephone, online and/or be solely based on written submissions, the specific manner to be chosen by the party initiating the arbitration; (b) the arbitration will not require any personal appearance by the parties or witnesses unless otherwise mutually agreed in writing by the parties; and (c) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.</p>
<p>(c) No Class Actions. YOU ANDMYDANCR LLC AGREE THAT YOU AND MYDANCR LLC MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. FURTHER, YOU AGREE THAT THE ARBITRATOR MAY NOT CONSOLIDATE PROCEEDINGS OF MORE THAN ONE PERSON’S CLAIMS, AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING, AND THAT IF THIS SPECIFIC PROVISO IS FOUND TO BE UNENFORCEABLE, THEN THIS ONLY THIS SECTION OF THIS MANDATORY ARBITRATION SECTION WILL BE NULL AND VOID.</p>
<p>(d) Decision of the Arbitrator. Barring extraordinary circumstances, the arbitrator will issue his or her decision within 180 days from the date the arbitrator is appointed. The arbitrator may extend this time limit for an additional 30 days in the interests of justice. All arbitration proceedings will be closed to the public and confidential and all records relating thereto will be permanently sealed, except as necessary to obtain court confirmation of the arbitration award. The award of the arbitrator will be in writing and will include a statement setting forth the reasons for the disposition of any claim. The arbitrator will apply the laws of the State of California in conducting the arbitration. You acknowledge that these terms and your use of the Service evidences a transaction involving interstate commerce. The United States Federal Arbitration Act will govern the interpretation, enforcement, and proceedings pursuant to the Mandatory Arbitration clause in this agreement.</p>
<p>(e) Equitable Relief. The foregoing provisions of this Dispute Resolution section do not apply to any claim in which either party seeks equitable relief to protect such party’s copyrights, trademarks, or patents. You acknowledge that, in the event of a breach of the agreement by MyDancr LLC or any third party, the damage or harm, if any, caused to you will not entitle you to seek injunctive or other equitable relief against MyDancr LLC, and your only remedy will be for monetary damages, subject to the limitations of liability set forth in this agreement.</p>
<h2 id="dancer-agreement-section-22">GOVERNING LAW.</h2><p>The laws of the State of California, excluding its conflicts of law rules, govern your use of the Service. Your use of the Service may also be subject to other local, state, national, or international laws. To the extent that any action relating to any dispute hereunder is permitted to be brought in a court of law, such action will be subject to the exclusive jurisdiction of the state and federal courts located in Los Angeles County, California, and you hereby irrevocably submit to personal jurisdiction in such courts and waive any defense of inconvenient forum. Any lawsuit filed in federal court shall be brought in the United States District Court for the Central District of California. PLEASE NOTE THAT BY AGREEING TO THIS AGREEMENT, YOU ARE WAIVING CLAIMS THAT YOU MIGHT OTHERWISE HAVE AGAINST US BASED ON THE LAWS OF OTHER JURISDICTIONS, INCLUDING YOUR OWN.</p>
<h2 id="dancer-agreement-section-23">RECOVERY OF EXPENSES.</h2><p>In any proceedings between the parties arising out of or relating to claims of intellectual property infringement, the prevailing party will be entitled to recover from the other party, in addition to any other relief awarded, all expenses that the prevailing party incurs in those proceedings, including legal fees and expenses. For purposes of section, “prevailing party” means, for any proceedings, the party in whose favor an award is rendered, except that if in those proceedings the award finds in favor of one party on one or more claims or counterclaims and in favor of the other party on one or more other claims or counterclaims, neither party will be the prevailing party. If any proceedings are voluntarily dismissed or are dismissed as part of settlement of that dispute, neither party will be the prevailing party in those proceedings.</p>
<h2 id="dancer-agreement-section-24">JURY TRIAL WAIVER.</h2><p>Each party hereby waives its right to a trial by jury in any claims arising out of or relating to the subject matter of this agreement. Either party may enforce this waiver up to and including the first day of trial.</p>
<h2 id="dancer-agreement-section-25">ASSIGNMENT.</h2><p>You may not assign this agreement or any of the rights or licenses granted hereunder, directly or indirectly, without the prior written consent of MyDancr LLC. This means that in the event you dispose of any device on which you have installed the Service, such as by sale or gift, you are responsible for deleting the Service from your mobile device prior to such disposition. MyDancr LLC may assign this agreement, including all its rights hereunder, without restriction. Any assignment in violation of this Section is void.</p>
<h2 id="dancer-agreement-section-26">MISCELLANEOUS.</h2><p>This agreement, together with the Privacy Policy and any other agreements expressly incorporated by reference herein, constitute the entire and exclusive understanding and agreement between you and MyDancr LLC regarding your use of and access to the Service, and, except as expressly permitted above, may be amended only by a written agreement signed by you and an authorized representative of MyDancr LLC. The failure to require performance of any provision will not affect our right to require performance at any time thereafter, nor will a waiver of any breach or default of this agreement or any provision of this agreement constitute a waiver of any subsequent breach or default or a waiver of the provision itself. Use of section headers in this agreement is for convenience only and will not have any impact on the interpretation of particular provisions. In the event that any part of this agreement is held to be invalid or unenforceable, the unenforceable part will be given effect to the greatest extent possible and the remaining parts will remain in full force and effect. You agree that no joint venture, partnership, employment, or agency relationship exists between you and MyDancr LLC as a result of this agreement or use of the Service. You acknowledge and agree thatMyDancr LLC and MyDancr LLC&#x27;s subsidiaries, and that MyDancr LLC will have the right to enforce this agreement against you as a third-party beneficiary thereof. The English language version of this agreement is the version that governs your use of the Service and in the event of any conflict between the English language version and a translated version, the English language version will control. You expressly agree that this agreement and all ancillary documents be drafted solely in English.</p>
<p>Your access to this Website and access to and use of the Service is governed by and conditioned on your express consent to this agreement. You have thoroughly reviewed this agreement to your satisfaction. By clicking on the “JOIN” button, you agree to be bound by this agreement, just as if you had signed it in pen and ink.</p>$document$, 'I agree to the Dancer Agreement.');

create table public.dancer_agreement_acceptances (
  user_id uuid not null references auth.users(id) on delete cascade,
  version text not null references public.dancer_agreement_versions(version),
  accepted_at timestamptz not null default clock_timestamp(),
  acceptance_source text not null check (acceptance_source in ('signup', 'dashboard')),
  primary key (user_id, version)
);
create table public.dancer_agreement_signup_intents (
  token uuid primary key default gen_random_uuid(),
  email text not null,
  version text not null references public.dancer_agreement_versions(version),
  accepted_at timestamptz not null default clock_timestamp(),
  expires_at timestamptz not null default (clock_timestamp() + interval '1 hour')
);
create index dancer_agreement_signup_expiry on public.dancer_agreement_signup_intents(expires_at);

alter table public.dancer_agreement_versions enable row level security;
alter table public.dancer_agreement_acceptances enable row level security;
alter table public.dancer_agreement_signup_intents enable row level security;
revoke all on public.dancer_agreement_versions, public.dancer_agreement_acceptances, public.dancer_agreement_signup_intents from public, anon, authenticated, service_role;
grant select on public.dancer_agreement_versions, public.dancer_agreement_acceptances to service_role;

create function public.dancer_agreement_access() returns jsonb
language plpgsql stable security definer set search_path = '' as $function$
declare
  current_version text;
  accepted_time timestamptz;
  required boolean;
begin
  if auth.uid() is null then raise exception 'Sign in required.' using errcode = '42501'; end if;
  select v.version into strict current_version from public.dancer_agreement_versions v where v.is_current;
  select a.accepted_at into accepted_time from public.dancer_agreement_acceptances a
    where a.user_id = auth.uid() and a.version = current_version;
  select exists(select 1 from public.app_users u where u.id = auth.uid() and u.role = 'dancer' and u.account_state = 'active') into required;
  return jsonb_build_object('required', required, 'accepted', accepted_time is not null,
    'version', current_version, 'acceptedAt', accepted_time);
end;
$function$;

create function public.accept_dancer_agreement(p_version text, p_accepted boolean) returns jsonb
language plpgsql security definer set search_path = '' as $function$
begin
  if auth.uid() is null then raise exception 'Sign in required.' using errcode = '42501'; end if;
  perform 1 from public.app_users u where u.id = auth.uid() and u.role = 'dancer' and u.account_state = 'active' for share;
  if not found then raise exception 'An active dancer account is required.' using errcode = '42501'; end if;
  if p_accepted is distinct from true or not exists (
    select 1 from public.dancer_agreement_versions v where v.version = p_version and v.is_current
  ) then raise exception 'Accept the current Dancer Agreement.' using errcode = '22023'; end if;
  insert into public.dancer_agreement_acceptances(user_id, version, acceptance_source)
    values(auth.uid(), p_version, 'dashboard') on conflict (user_id, version) do nothing;
  return public.dancer_agreement_access();
end;
$function$;

create function public.prepare_dancer_agreement_signup(p_email text, p_version text) returns uuid
language plpgsql security definer set search_path = '' as $function$
declare intent uuid;
begin
  if length(p_email) > 254 or p_email is null or p_email not like '%@%'
    or not exists(select 1 from public.dancer_agreement_versions v where v.version = p_version and v.is_current)
    then raise exception 'Invalid agreement signup request.' using errcode = '22023'; end if;
  delete from public.dancer_agreement_signup_intents where expires_at < clock_timestamp();
  insert into public.dancer_agreement_signup_intents(email, version)
    values(lower(btrim(p_email)), p_version) returning token into intent;
  return intent;
end;
$function$;

create function public.attach_dancer_signup_agreement() returns trigger
language plpgsql security definer set search_path = '' as $function$
declare intent public.dancer_agreement_signup_intents%rowtype;
begin
  if new.raw_user_meta_data->>'role' = 'dancer' then
    delete from public.dancer_agreement_signup_intents i
      where i.token::text = new.raw_user_meta_data->>'dancer_agreement_intent'
      and i.email = lower(btrim(new.email)) and i.expires_at > clock_timestamp()
      returning i.* into intent;
    if found then
      insert into public.dancer_agreement_acceptances(user_id, version, accepted_at, acceptance_source)
        values(new.id, intent.version, intent.accepted_at, 'signup');
    end if;
  end if;
  return new;
end;
$function$;
-- INSERT only: duplicate signups or later metadata edits cannot accept for an
-- existing identity. Failure to save the receipt rolls back the new Auth user.
create trigger attach_dancer_signup_agreement after insert on auth.users
  for each row execute function public.attach_dancer_signup_agreement();

revoke all on function public.dancer_agreement_access(), public.accept_dancer_agreement(text, boolean),
  public.prepare_dancer_agreement_signup(text, text), public.attach_dancer_signup_agreement() from public, anon, authenticated, service_role;
grant execute on function public.dancer_agreement_access(), public.accept_dancer_agreement(text, boolean) to authenticated;
grant execute on function public.prepare_dancer_agreement_signup(text, text) to service_role;

notify pgrst, 'reload schema';
commit;
