-- Browser requests use row-level CRUD, never bulk or schema maintenance.
-- Explicit reviewed tables only; preserve all row/column, server and policy grants.
begin;
set local lock_timeout = '3s';
set local statement_timeout = '30s';

revoke truncate, references, trigger, maintain on table
  public.agent_commission_events,
  public.app_users,
  public.approval_reviews,
  public.club_deals,
  public.club_finance_accounts,
  public.club_invoice_items,
  public.club_invoice_reminders,
  public.club_invoices,
  public.commission_events,
  public.content_reports,
  public.customer_profiles,
  public.dancer_earning_status_history,
  public.dancer_nfc_enrollments,
  public.dancer_payout_accounts,
  public.dancer_payout_batches,
  public.dancer_payout_items,
  public.dancer_photos,
  public.dancer_profiles,
  public.deal_revenue_events,
  public.direction_requests,
  public.dmca_agent_settings,
  public.dmca_cases,
  public.dmca_counter_notices,
  public.dmca_strikes,
  public.favorites,
  public.financial_audit_events,
  public.follows,
  public.going_signals,
  public.image_moderation_records,
  public.mydancr_tv_events,
  public.mydancr_tv_videos,
  public.nats_affiliate_accounts,
  public.nats_agent_affiliate_accounts,
  public.nats_agent_commission_exports,
  public.nats_commission_exports,
  public.nfc_tags,
  public.nfc_tap_events,
  public.notifications,
  public.payment_provider_webhook_events,
  public.payout_settings,
  public.profile_views,
  public.qr_redemption_events,
  public.qr_redemptions,
  public.ranking_events,
  public.sales_agents,
  public.schedule_views,
  public.shifts,
  public.social_clicks,
  public.social_links,
  public.subscriptions,
  public.support_ai_runs,
  public.support_messages,
  public.support_threads,
  public.trending_scores,
  public.venue_activity_log,
  public.venue_club_deal_requests,
  public.venue_follows,
  public.venue_nfc_support_requests,
  public.venue_ownership_claims,
  public.venue_page_events,
  public.venue_pilot_night_reports,
  public.venue_referral_fee_change_requests,
  public.venue_referral_fee_terms,
  public.venue_sales_attributions,
  public.venue_team_invitations,
  public.venue_team_members,
  public.venues
from public, anon, authenticated;

commit;
